dreamtravel_project/dreamtravel_project/urls.py
from django.contrib import admin
from django.urls import path, include
#from app_siteweb.views import home_page,index
#from app_siteweb.views import index, login

# from django.urls import settings
from django.conf import settings
from django.conf.urls.static import static


#.views.py import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include ("user_app.urls")),
    path("", include("app_siteweb.urls")),  
    path("scrapping/",include("scraping_app.urls")),
    #path("login_register/",include("app_siteweb.urls")),
   # path("",index)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dreamtravel_project/scraping_app/urls.py
from django.urls import path
from . import views
app_name = 'scraping_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('scrape/', views.scrape, name='scrape'),
    path('download/', views.download_file, name='download_file'),
    # Ensure a URL pattern for the redirect exists
    path('results/', views.scrape_results, name='scrape_results'),  # Add this
]

dreamtravel_project/user_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = 'user_app'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(http_method_names=['post']), name='logout'),  # Accepter POST uniquement
    
]

dreamtravel_project/scraping_app/models.py
from django.db import models

# Create your models here.

dreamtravel_project/scraping_app/views.py
from django.shortcuts import render , redirect
import requests
from django.template import TemplateDoesNotExist
from bs4 import BeautifulSoup
from io import BytesIO
from reportlab.pdfgen import canvas
from django.http import HttpResponse
import csv
import json
from django.urls import path
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.shortcuts import render, redirect
import requests
from bs4 import BeautifulSoup
from app_siteweb.models import Hotel, Image
from decimal import Decimal
from django.core.files.base import ContentFile
import os





from django.shortcuts import render, redirect
from playwright.sync_api import sync_playwright
from django.http import HttpResponse
from decimal import Decimal
from app_siteweb.models import Hotel, Image  # Adjust based on your app's name
import os
from django.core.files.base import ContentFile
import pandas as pd

def scrape(request):
    if request.method == 'POST':
        try:
            with sync_playwright() as p:
                checkin_date = '2024-06-24'  # You can make these dynamic
                checkout_date = '2024-06-28'
                
                page_url = f'https://www.booking.com/searchresults.es.html?ss=Marrakech&checkin={checkin_date}&checkout={checkout_date}'
                browser = p.chromium.launch(headless=True)  # Set to False if you want to see the browser
                page = browser.new_page()
                page.goto(page_url, timeout=60000)  # Adjust timeout
                
                # Find all hotels
                hotel_elements = page.locator('//div[@data-testid="property-card"]').all()
                
                for hotel_element in hotel_elements:
                    # Extract hotel information
                    nom = hotel_element.locator('//div[@data-testid="title"]').inner_text(strip=True)
                    emplacement = hotel_element.locator('//span[@data-testid="property-card__address"]').inner_text(strip=True)
                    
                    # Default description
                    description = 'Aucune description fournie'
                    
                    # Extract price and promotion
                    prix_element = hotel_element.locator('//span[@data-testid="price-and-discounted-price"]').inner_text(strip=True)
                    prix = Decimal(prix_element.replace("MAD", "").replace("\u00a0", ""))
                    
                    promo = 0
                    promo_element = hotel_element.locator('//span[@data-testid="price-and-discounted-price__old-price"]')
                    if promo_element:
                        prix_avec_promo = Decimal(promo_element.inner_text(strip=True).replace("MAD", "").replace("\u00a0", ""))
                        if prix_avec_promo > prix:
                            promo = ((prix_avec_promo - prix) / prix_avec_promo) * 100
                    
                    # Create or update the Hotel model
                    hotel, created = Hotel.objects.update_or_create(
                        nom=nom,
                        defaults={
                            'emplacement': emplacement,
                            'description': description,
                            'prix': prix,
                            'promo': promo
                        }
                    )
                    
                    # Extract and save images
                    image_elements = hotel_element.locator('//img').all()  # Adjust if necessary
                    for img in image_elements:
                        img_url = img.get('src')
                        if img_url:
                            img_resp = requests.get(img_url)
                            if img_resp.status_code == 200:
                                img_name = os.path.basename(img_url)
                                new_image = Image()
                                new_image.image.save(img_name, ContentFile(img_resp.content), save=True)
                                hotel.photos.add(new_image)

                # Close the browser
                browser.close()

            return redirect('scraping_app:scrape_results')  # Redirect to the results page
        except Exception as e:
            return render(request, 'scrap/home.html', {'error': f"An error occurred: {e}"})
    else:
        return render(request, 'scrap/home.html')








def home(request):
    return render(request, 'scrap/home.html')




def scrape_results(request):
    try:
        hotels = Hotel.objects.all()  # Retrieve all hotels
        return render(request, 'scrap/result.html', {'hotels': hotels})
    except TemplateDoesNotExist as e:
        return HttpResponse(f"Template not found: {e}")
    
def download_file(request):
    if 'scraped_data' in request.session:
        context = request.session['scraped_data']
        response = HttpResponse(content_type='')
        if request.POST['download_type'] == 'pdf':
            template_path = 'result.html'
            template = get_template(template_path)
            html = template.render(context)
            response = HttpResponse(content_type='application/pdf')
            filename = f"{context['title']}.pdf"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            buffer = BytesIO()
            pisa_status = pisa.CreatePDF(html, dest=response, encoding='utf-8')
            if pisa_status.err:
                return HttpResponse('PDF generation failed')
        elif request.POST['download_type'] == 'csv':
            response = HttpResponse(content_type='text/csv')
            filename = f"{context['title']}.csv"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            writer = csv.writer(response)
            writer.writerow(['Title', 'Headings', 'Paragraphs'])
            rows = zip([context['title']], context['headings'], context['paragraphs'])
            for row in rows:
                writer.writerow(row)
        elif request.POST['download_type'] == 'json':
            response = HttpResponse(content_type='application/json')
            filename = f"{context['title']}.json"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            json.dump(context, response, indent=4)
        return response
    else:
        return render(request, 'scrap/home.html')

dreamtravel_project/scraping_app/templates/scrap/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>Web Scraper</title>
 <style>
  body {
   margin: 0;
   padding: 0;
   font-family: Arial, sans-serif;
   background-color: #f2f2f2;
  }
  h1 {
   margin: 20px;
   text-align: center;
   font-size: 40px;
   color: #333;
  }
  form {
   display: flex;
   flex-direction: column;
   align-items: center;
   margin-top: 50px;
  }
  input[type="text"] {
   padding: 10px;
   border: none;
   border-radius: 5px;
   box-shadow: 0 2px 5px rgba(0,0,0,0.2);
   margin-bottom: 20px;
   width: 400px;
  }
  button[type="submit"] {
   padding: 10px 20px;
   background-color: #4CAF50;
   color: white;
   border: none;
   border-radius: 5px;
   cursor: pointer;
   box-shadow: 0 2px 5px rgba(0,0,0,0.2);
  }
  button[type="submit"]:hover {
   background-color: #3e8e41;
  }
 </style>
 <link rel="stylesheet" href="{% static 'w3.css' %}">
</head>
<body><h1>Web Scraper</h1>
<form method="post" action="{% url 'scraping_app:scrape' %}">  
  {% csrf_token %}
  <input type="text" name="url" placeholder="Enter URL here...">
  <button type="submit">Scrape</button>
 </form>

 <br>

</body>
</html>

dreamtravel_project/scraping_app/templates/scrap/result.html
<!DOCTYPE html>
<html>
<head>
 <title>Scraped Data</title>
 <style>
  body {
   font-family: Arial, sans-serif;
   background-color: #f2f2f2;
   margin: 0;
   padding: 0;
  }

  .container {
   max-width: 800px;
   margin: 0 auto;
   padding: 20px;
   background-color: #fff;
   box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
   overflow-y: scroll; 
   height: 500px; 
  }

  h1 {
   font-size: 36px;
   color: #333;
   margin-top: 0;
  }

  h2 {
   font-size: 24px;
   color: #333;
   margin-top: 30px;
   margin-bottom: 10px;
  }

  p {
   font-size: 16px;
   color: #666;
   line-height: 1.5;
   margin-top: 0;
  }

 
  .button {
   background-color: #4CAF50;
   border: none;
   color: white;
   padding: 15px 32px;
   text-align: center;
   text-decoration: none;
   display: inline-block;
   font-size: 16px;
   margin: 4px 2px;
   cursor: pointer;
   border-radius: 5px;
   box-shadow: 0 2px 5px rgba(0,0,0,0.2);
  }

 
  .button:hover {
   background-color: #3e8e41;
  }

  
 </style>
 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
 <br><br>
 <div class="container">
  <h1>{{ title }}</h1>
  {% for heading in headings %}
   <h2>{{ heading }}</h2>
  {% endfor %}
  {% for paragraph in paragraphs %}
   <p>{{ paragraph }}</p>
  {% endfor %}
  
 </div>
 
 <br><br>
 
    
 <div class="w3-container" style="margin:auto; width:50%; text-align:center;">
  <form method="POST" action="{% url 'scraping_app:download_file' %}">
   {% csrf_token %}
   <h3>Download Option</h3>
    
   <select class="w3-select" id="download_type" name="download_type">
     <option value="" disabled selected>Choose your option</option>
     <option value="pdf">PDF</option>
     <option value="csv">CSV</option>
     <option value="json">JSON</option>
   </select>
    <br><br>
   <p><button type="submit" class="w3-btn w3-teal">Download</button></p>

   <a href="{% url 'scraping_app:home' %}">
    <button class="w3-button w3-teal w3-center" style="margin:auto">Go Back</button>
   </a>
    
    </form>
 </div>
 <br><br>
     
</body>
</html>