dreamtravel_project/app_siteweb/urls.py
from django.urls import path
from app_siteweb.views import fake,home_page,essai_hotel,hotel_detail,activite_detail,restaurant_detail,ask_question,chat
# from app_siteweb import views
app_name = 'app_siteweb'
urlpatterns = [
    #path("home", home_page, name='homepage'),
    path("essai", fake,name='fake'),
    path("", home_page, name='home'),
    path("mamounia", essai_hotel),
    path('hotel/<str:slug>',hotel_detail,name='hotel-detail'),
    path('activite/<str:slug>',activite_detail,name='activite-detail'),
    path('restaurant/<str:slug>',restaurant_detail,name='restaurant-detail'),
    path('ask_question/', ask_question, name='ask_question'),  # Assurez-vous que ce chemin est correct
    path('chat/', chat, name='chat'),  # Ceci doit correspondre à la vue
]

#from app_siteweb import views
#  path("", views.index),
    

dreamtravel_project/dreamtravel_project/urls.py
from django.contrib import admin
from django.urls import path, include
#from app_siteweb.views import home_page,index
#from app_siteweb.views import index, login

# from django.urls import settings
from django.conf import settings
from django.conf.urls.static import static


#.views.py import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include ("user_app.urls")),
    path("", include("app_siteweb.urls")),  
    path("scrapping/",include("scraping_app.urls")),
    #path("login_register/",include("app_siteweb.urls")),
   # path("",index)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dreamtravel_project/user_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = 'user_app'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(http_method_names=['post']), name='logout'),  # Accepter POST uniquement
    
]

dreamtravel_project/templates/accueil/activite_detail.html
{% extends "accueil/base1.html" %} {% load static %}
<!-- Load the 'static' tag -->

{% block extra_css %}
<!-- Additional CSS specific to this template -->
<link rel="stylesheet" href="{% static 'assets/css/place.css' %}" />
{% endblock %} {% block content %}
<div class="card-wrapper" style="margin-top: 20px">
  <div class="card">
    <!-- Card left -->
    <div class="product-imgs">
      <div class="img-display">
        <div class="img-showcase">
          <!-- Loop for main images -->
          {% for image in activite.images.all %}
          <img src="{{ image.image.url }}" alt="{{ activite.nom }}" />
          {% endfor %}
        </div>
      </div>
      <div class="img-select">
        <!-- Loop for selectable thumbnails -->
        {% for image in activite.images.all %}
        <div class="img-item">
          <a href="#" data-id="{{ forloop.counter }}">
            <img src="{{ image.image.url }}" alt="{{ activite.nom }}" />
          </a>
        </div>
        {% endfor %}
      </div>
    </div>

    <!-- Card right -->
    <div class="product-content">
      <h2 class="product-title">{{ activite.nom }}</h2>
      <a href="https://shorturl.at/afS09" class="product-link">For Booking</a>

      <div class="product-rating">
        <!-- Display stars based on rating -->
        {% for _ in activite.rate_range %}
        <i class="fas fa-star"></i>
        {% endfor %} {% for _ in activite.neg_rate_range %}
        <i class="far fa-star"></i>
        {% endfor %}
        <!-- Display total reviews -->
        <span>{{ activite.rating }} ({{ activite.reviews.count }})</span>
      </div>

      <div class="product-duration">
        <p class="duration-info">
          <i class="fa-solid fa-clock"></i>
          Durée: <span>{{ activite.duree }}</span>
          <!-- Display duration -->
        </p>
      </div>

      <div class="product-detail">
        <h2>About this Activity:</h2>
        <p>{{ activite.description }}</p>
        <!-- Display description -->
      </div>

      <div class="social-links">
        <!-- Social media links -->
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-whatsapp"></i></a>
        <a href="#"><i class="fab fa-pinterest"></i></a>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'assets/js/place.js' %}"></script>

{% endblock %}

dreamtravel_project/templates/accueil/activite_detail_backup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ hotel.nom }} - Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'assets/css/place.css' %}" />
    <link
      rel="stylesheet"
      <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    />
  </head>
  <body>
    <div class="card-wrapper">
      <div class="card">
        <!-- card left -->
        <div class="product-imgs">
          <div class="img-display">
            <div class="img-showcase">
              <!-- Loop to display hotel photos -->
              {% for photo in hotel.photos.all %}
              <img src="{{ photo.image.url }}" alt="{{ hotel.nom }} photo" />
              {% endfor %}
            </div>
          </div>
          <div class="img-select">
            <!-- Loop for selectable thumbnails -->
            {% for photo in hotel.photos.all %}
            <div class="img-item">
              <a href="#" data-id="{{ forloop.counter }}">
                <!-- Use forloop.counter for index -->
                <img
                  src="{{ photo.image.url }}"
                  alt="{{ hotel.nom }} thumbnail"
                />
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
        <!-- card right -->
        <div class="product-content">
          <h2 class="product-title">{{ hotel.nom }}</h2>
          <a href="https://shorturl.at/afS09" class="product-link"
            >For Booking</a
          >

          <div class="product-rating">
            <!-- Display hotel rating with stars -->
            {% for _ in hotel.rate_range %}
            <i class="fas fa-star"></i>
            {% endfor %} {% for _ in hotel.neg_rate_range %}
            <i class="far fa-star"></i>
            {% endfor %}
            <span>{{ hotel.rating }}</span>
          </div>

          <div class="product-price">
            <p class="last-price">
              <!-- Old Price with an icon -->
              <i class="fa-solid fa-tag"></i>
              <!-- Icon representing the regular price -->
              Old Price: <span>{{ hotel.prix }} MAD</span>
            </p>
            <p class="new-price">
              <!-- Conditionally include the icon if there's a promotion -->
              {% if hotel.promo > 0 %}
              <i class="fa-solid fa-coins"></i>
              <!-- Icon indicating the promotional price -->
              New Price:
              <span>{{ hotel.calculate_total_price_with_promotion }} MAD</span>
              {% else %} New Price: <span>{{ hotel.prix }} MAD</span>
              {% endif %}
            </p>
          </div>

          <div class="product-detail">
            <h2>About This Hotel:</h2>
            <p>{{ hotel.description }}</p>
          </div>

          <div class="social-links">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-whatsapp"></i></a>
            <a href="#"><i class="fab fa-pinterest"></i></a>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'assets/js/place.js' %}"></script>
  </body>
</html>

dreamtravel_project/templates/accueil/activite_list.html
{% load static %}

<section class="packages" id="activite">
  <h1 class="heading">
    <span>A</span>
    <span>C</span>
    <span>T</span>
    <span>I</span>
    <span>V</span>
    <span>I</span>
    <span>T</span>
    <span>E</span>
    <span>S</span>
  </h1>

  <div class="box-container">
    {%for act in activites %}
    <div class="box">
      {% with act.images.first as photo %} {% if photo %}
      <img src="{{ photo.image.url }}" alt="{{ act.nom }}" />
      {% else %}
      <img src="{% static 'assets/images/placeholder.png' %}" alt="No image" />
      {% endif %} {% endwith %}
      <div class="content">
        <h3><i class="fas fa-map-market-alt"></i> {{ act.nom }}</h3>
        <p>{{ act.description }}</p>
        {% load custom_filters %}
        <div
          class="stars"
          style="
            display: flex;
            justify-content: space-between;
            align-items: center;
          "
        >
          <div class="stars-icons">
            {% for _ in act.rate_range %}
            <i class="fas fa-star"></i>
            {% endfor %} {% for _ in act.neg_rate_range %}
            <i class="far fa-star"></i>
            {% endfor %}
          </div>
          <div class="time-info" style="display: flex; align-items: center">
            <i class="fa-solid fa-clock"></i>
            <!-- Icône d'horloge -->
            <span style="margin-left: 5px; font-weight: bold"
              >{{act.duree}}</span
            >
          </div>
        </div>
        <br />
        <a
          href="{% url 'app_siteweb:activite-detail' slug=act.slug %}"
          class="btn"
        >
          View More</a
        >
      </div>
    </div>
    {% endfor %}
  </div>
</section>

dreamtravel_project/templates/accueil/base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>tourist site web</title>

    <!-- Liaisons CSS générales -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    {% block extra_css %} {% endblock %}
  </head>
  <body>
    <header>
      <div id="menu-bar" class="fas fa-bars"></div>
      <a href="#" class="logo"><span>Dream</span>Travel</a>
      <nav class="navbar">
        <a href="#home">home</a>
        <a href="#gallery">places</a>
        <a href="#services">services</a>
        <a href="#review">review</a>
        <a href="#contact">contact</a>
      </nav>
    </header>
    <!-- Contenu du template de base -->
  </body>
</html>

dreamtravel_project/templates/accueil/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dream Travel{% endblock %}</title>

    <!-- Liens CSS de base -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> <!-- Font Awesome 6 -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    
    <!-- Bloc CSS supplémentaire -->
    {% block extra_css %}{% endblock %}
</head>
<body>
    <!-- Bloc d'en-tête -->
    <header>
        <div id="menu-bar" class="fas fa-bars"></div>
        <a href="#" class="logo"><span>Dream</span>Travel</a>
        <nav class="navbar">
    <a href="{% url 'app_siteweb:home' %}">Home</a>
    <a href="{% url 'app_siteweb:home' %}#places">Places</a>
    <a href="{% url 'app_siteweb:home' %}#hotels">Hotels</a>
    <a href="{% url 'app_siteweb:home' %}#restaurant">Restaurant</a>
    <a href="{% url 'app_siteweb:home' %}#activite">Activite</a>
</nav>

        
        <div class="icons">
            {% if request.user.is_authenticated %}
                <!-- Bouton de déconnexion -->
                <button class="btn btn-primary" style="border-radius: 99em;" onclick="logoutUser();">Log Out</button>

                <script>
                function logoutUser() {
                    fetch("{% url 'user_app:logout' %}", {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}'
                        }
                    }).then(() => {
                        // Redirection après la déconnexion
                        window.location.href = "{% url 'app_siteweb:home' %}";
                    }).catch(error => {
                        console.error("Erreur de déconnexion :", error);
                    });
                }
                </script>

<!-- Le bouton qui doit être masqué si vous êtes déjà sur /chat/ -->
<button id="chatbot-button" class="btn btn-primary" style="border-radius: 99em;"onclick="window.location.href='{% url 'app_siteweb:chat' %}'">Chatbot</button>
</button>

<!-- Script pour masquer le bouton si la page est /chat/ -->
<script>
document.addEventListener("DOMContentLoaded", function() {
    var currentPath = window.location.pathname;  // Obtenir le chemin actuel de la page
    
    if (currentPath === "/chat/") {
        var chatbotButton = document.getElementById("chatbot-button");
        chatbotButton.style.display = 'none';  // Masquer le bouton
    }
});
</script>

            {% else %}
                <!-- Boutons de connexion et d'inscription -->
                <button class="btn btn-primary" style="border-radius: 99em;" onclick="window.location.href='{% url 'user_app:login' %}'">Login</button>
                <button class="btn btn-primary" style="border-radius: 99em;" onclick="window.location.href='{% url 'user_app:signup' %}'">Register</button>
            {% endif %}
        </div>
    </header>

    <!-- Bloc de contenu principal -->
    {% block content %}
    <!-- Contenu par défaut pour les pages utilisant ce modèle -->
    {% endblock %}

    <!-- Bloc JavaScript supplémentaire -->
    {% block extra_js %}
    <!-- <script src="{% static 'assets/js/custom.js' %}"></script> -->
    {% endblock %}
</body>
</html>

dreamtravel_project/templates/accueil/base_login_register.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %} | login_registre</title>
  </head>

  <body>
    <nav
      class="py-6 px-6 flex justify-between items-center border-b border-gray-200"
    >
      <a href="/" class="text-xl font-semibold">Dream Travel</a>

      <div class="space-x-6">
        <a
          href="{% url 'item:new' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >New item</a
        >
        <a
          href="{% url 'item:items' %}"
          class="text-lg font-semibold hover:text-gray-500"
          >Browse</a
        >

        {% if request.user.is_authenticated %}
        <a
          href="{% url 'app_siteweb:home' %}"
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
          >home</a
        >
        <a
          href="{% url 'app_siteweb:home' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
          >Dashboard</a
        >
        {% else %}
        <a
          href="{% url 'user_app:signup' %}"
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
          >Sign up</a
        >
        <a
          href="{% url 'user_app:login' %}"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
          >Log in</a
        >
        {% endif %}
      </div>
    </nav>

    <div class="px-6 py-6">{% block content %} {% endblock %}</div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>

        <p class="text-lg text-gray-500">
          Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla
          bla.
        </p>
      </div>

      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700"
              >About</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700"
              >Privacy policy</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teal-700"
              >Term of use</a
            >
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

dreamtravel_project/templates/accueil/chatbot.html
{% extends "accueil/base1.html" %}
{% load static %}

{% block extra_css %} 
<link rel="stylesheet" href="{% static 'assets/css/chatbot.css' %}" />
{% endblock %}

{% block content %}
<section class="contact" id="contact" style="margin-top: 90px">
    

    <div class="chatbot-container">
        <h1 class="heading">
        <span>c</span>
        <span>h</span>
        <span>a</span>
        <span>t</span>
        <span>b</span>
        <span>o</span>
        <span>t</span>
    </h1>
    <div id="header">
            <h1>Chatbot</h1>
        </div>
        <div id="chatbot">
            <div id="conversation">
                {% if chats %}
                    {% for chat in chats %}
                        <div class="chatbot-message user-message">
                            <p class="chatbot-text">{{ chat.text_input }}</p>
                        </div>
                        <div class="chatbot-message chatbot-message">
                            <p class="chatbot-text">{{ chat.gemini_output | safe }}</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="chatbot-message">
                        <p class="chatbot-text">Hi! 👋 it's great to see you!</p>
                    </div>
                {% endif %}
            </div>
            <form id="input-form" onsubmit="askQuestion(event)">
                <message-container>
                <input id="input-field" type="text" placeholder="Type your message here">
                <button id="submit-button" type="submit">
                    <img class="send-icon" src="{% static 'assets/images/send-message.png' %}" alt="Send Message Icon">  
                </button>
              </message-container>
            </form>
        </div>
    </div>
</section>
<script src="{% static 'assets/js/chatbot.js' %}"></script>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js"></script>
{% endblock %}

dreamtravel_project/templates/accueil/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tourist site web </title>

    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">  <!-- Font Awesome 6 -->

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/chatbot.css" %}">

</head>
<body>
    
<!-- header section starts  -->

<header>

    <div id="menu-bar" class="fas fa-bars"></div>

    <a href="#" class="logo"><span>Dream</span>Travel</a>

    <nav class="navbar">
        <a href="#home">home</a>
        <a href="#places">places</a>
        <a href="#hotels">hotels</a>
        <a href="#restaurant">restaurant</a>
        <a href="#activite">activite</a>
    </nav>

    <div class="icons">
        {% if request.user.is_authenticated %}

<!-- Bouton de déconnexion -->
<button class="btn btn-primary" style="border-radius: 99em;" 
        onclick="logoutUser();">
    Log Out
</button>

<script>
function logoutUser() {
    fetch("{% url 'user_app:logout' %}", {
        method: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        }
    }).then(() => {
        // Rediriger après la déconnexion
        window.location.href = "{% url 'app_siteweb:home' %}";
    }).catch(error => {
        console.error("Erreur de déconnexion :", error);
    });
}
</script>


<button type="button" class="btn btn-primary"
        style="border-radius: 99em;"
        onclick="window.location.href='{% url 'app_siteweb:chat' %}'">
    chatbot
</button>

        {% else %}
<button type="button" class="btn btn-primary" 
        style="border-radius: 99em;" 
        onclick="window.location.href='{% url 'user_app:login'%}'">
    Login
</button>
       <button type="button" class="btn btn-primary" 
        style="border-radius: 99em;" 
        onclick="window.location.href='{% url 'user_app:signup' %}'">
    register
</button>
        {% endif %}
    </div>

    
</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

    <div class="content">
    </div>

    <div class="controls">
        <span class="vid-btn active" data-src="{% static 'assets/images/imgs/1.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'assets/images/imgs/3.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'assets/images/imgs/2.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'assets/images/imgs/4.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'assets/images/imgs/5.jpg' %}"></span>
    </div>

    <div class="video-container">
        <img src="{% static 'assets/images/imgs/1.jpg' %}" id="video-slider" alt="Image Slider">
    </div>
    

</section>

<!-- home section ends -->

<!-- book section starts  -->

<section class="book" id="book">

    <h1 class="heading">
        <span>D</span>
        <span>E</span>
        <span>S</span>
        <span>T</span>
        <span>I</span>
        <span>N</span>
        <span>A</span>
        <span>T</span>
        <span>I</span>
        <span>O</span>
        <span>N</span>


    </h1>

    <div class="row">

        <div class="image">
            <img src="{% static 'assets/images/book-img.svg' %}" alt="">
        </div>

        <form action="">
            <div class="inputBox">
                <h3>where to</h3>
                <input type="text" placeholder="place name">
            </div>
            <div class="inputBox">
                <h3>how many</h3>
                <input type="number" placeholder="number of guests">
            </div>
            <div class="inputBox">
                <h3>arrivals</h3>
                <input type="date">
            </div>
            <div class="inputBox">
                <h3>leaving</h3>
                <input type="date">
            </div>
            <input type="submit" class="btn" value="book now">
        </form>

    </div>

</section>


{% block content_place %}

{% include "accueil/place_list.html" %} 

{% endblock %}

<section class="services" id="services">

    <h1 class="heading">
        <span>s</span>
        <span>e</span>
        <span>r</span>
        <span>v</span>
        <span>i</span>
        <span>c</span>
        <span>e</span>
        <span>s</span>
    </h1>

    <div class="box-container">

        <div class="box">
            <i class="fas fa-hotel"></i>
            <h3>affordable hotels</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>
        <div class="box">
            <i class="fas fa-utensils"></i>
            <h3>food and drinks</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>
        <div class="box">
            <i class="fas fa-hiking"></i>
            <h3>adventures</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>

    </div>

</section>

{% block content %}

{% include "accueil/hotel_list.html" %} 

{% include "accueil/restaurant_list.html" %} 

{% include "accueil/activite_list.html" %}

{% include "accueil/reviews.html" %}

{% endblock %}



<section class="footer">

    <div class="box-container">

        <div class="box">
            <h3>about us</h3>
            <p>About any doubt , feel free to contact us and enjoy the beautiful landscape and scenery of North-East India</p>
        </div>
        <div class="box">
            <h3>branch locations</h3>
            <a href="#">Assam</a>
            <a href="#">Sikkim</a>
            <a href="#">Arunachal Pradesh</a>
            <a href="#">Meghalaya</a>
        </div>
        <div class="box">
            <h3>quick links</h3>
            <a href="#">home</a>
            <a href="#">book</a>
            <a href="#">packages</a>
            <a href="#">services</a>
            <a href="#">gallery</a>
            <a href="#">review</a>
            <a href="#">contact</a>
        </div>
        

    </div>

    <h1 class="credit"> <span>|All Right Reserved|</span> </h1>

</section>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- custom js file link  -->
<script src="{% static 'assets/js/script.js' %}"></script> 
</body>
</html>

dreamtravel_project/templates/accueil/indez.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static "/assets/css/stylz.css" %}">
    <title>Authentification</title>
</head>

<body>

    <div class="container" id="container">
        <div class="form-container sign-up">
            <form>
                <h1>Create Account</h1>
                <br>

                <input type="text" placeholder="Name">
                <input type="email" placeholder="Email">
                <input type="password" placeholder="Password">
                <button>Sign Up</button>
            </form>
        </div>
        <div class="form-container sign-in">
            <form>
                <h1>Sign In</h1>

                <br>

                <input type="email" placeholder="Email">
                <input type="password" placeholder="Password">
                <a href="#">Forget Your Password?</a>
                <button>Sign In</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Welcome Back!</h1>
                    <p>Enter your personal details to use all of site features</p>
                    <button class="hidden" id="login">Sign In</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>Hello, Friend!</h1>
                    <p>Register with your personal details to use all of site features</p>
                    <button class="hidden" id="register">Sign Up</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'assets/js/scripz.js' %}"></script>
</body>

</html>